### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by takumu-mm** [takumu-mm/GolfApp#34]
## 各種情報
サービス名: GolfUp
サービスURL: https://golfup-app-afae12b6adfa.herokuapp.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [ ] 会員登録機能
- [ ] ログイン機能
- [ ] プロフィール機能
- [ ] おすすめ動画診断機能
- [ ] スキル別でコンテンツを提供する機能（カテゴリー機能）

## サービスイメージがわかるようなスクリーンショット等
特に管理画面など通常ユーザーが触れない機能はありません。

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。
