### ISSUE TITLE
Issueベース開発レビュー依頼

### ISSUE THREAD

**Issue by takumu-mm** [takumu-mm/GolfApp#4]
### 実装予定の機能
- [x] 会員登録
- [x] ログイン機能
- [x] プロフィール機能
- [x] スキル別でコンテンツを提供する機能
- [x] おすすめの動画診断機能
- [x] おすすめ動画 閲覧、投稿、編集、削除機能
- [x] おすすめ動画検索機能
- [x] コメント機能（投稿、編集、削除）

### 必要ページ
- [x] トップページ
- [x] 各カテゴリーのおすすめゴルフ動画ページ
- [x] ユーザー新規登録ページ
- [x] ログインページ
- [x] パスワード再設定ページ（Email送信ページ）
- [x] パスワード再設定ページ（パスワード変更ページ）
- [x] マイページ
- [x] マイページ編集ページ
- [x] ユーザー登録推奨ページ
- [x] ユーザーのおすすめ動画診断結果ページ
- [x] みんなのおすすめ動画共有一覧ページ
- [x] みんなのおすすめ動画共有検索ページ
- [x] みんなのおすすめ動画共有詳細ページ
- [x] みんなのおすすめ動画共有新規投稿ページ
- [x] みんなのおすすめ動画共有投稿編集ページ
- [x] プライバシーポリシーページ
- [x] 利用規約ページ
- [x] お問い合わせページ

**Comment by kenchasonakai** [comment]
> また、作成したGitHubProjectをpublicに変更して、URLの共有もお願いします。

上記ご対応お願いいたします

**Comment by kenchasonakai** [comment]
LGTMです！

おすすめ動画診断機能とHeroku初期デプロイは実装イメージや作業イメージが湧いていないから8なのか、やることを理解している上で8なのかどちらかによりますが前者であれば実装を始める前に調べて分解できるものがあったらissueを分解して進めていくと良いかと思います

**Comment by takumu-mm** [comment]
確認ありがとうございます。
実装イメージがまだ湧いていないため８にしました。実装前に分解しようと思います。
